#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user.
# nginx must be listening on all active IPs on port 8080
sudo su
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
