#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
# Requirements:
# The redirection must be a “301 Moved Permanently”
# You answer file should be a Bash script containing commands to automatically configure a Ubuntu machine to respect above requirements
# Using what you did with 1-install_nginx_web_server, write 3-redirection so that it configures a brand new Ubuntu machine to the requirements asked in this task
config="server_name _;\n\trewrite ^/redirect_me/$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
apt update
apt install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index.html
sed -i "s|server_name\ _;|$config|" /etc/nginx/sites-available/default
service nginx restart
