#!/usr/bin/env bash
# Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

#Requirements:

#he page must return an HTTP 404 error code
#The page must contain the string Ceci n'est pas une page
#Using what you did with 3-redirection, write 4-not_found_page_404 so that it configures a brand new Ubuntu machine to the requirements asked in this task


apt-get update
apt-get install -y nginx

sudo ufw allow 'Nginx HTTP'
sudo chown -R $USER:$USER /var/

mkdir -p /var/www/html
touch /var/www/html/index.html
echo "Hello World" > /var/www/html/index.html

touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

printf %s "server {
        root        /var/www/html/;
        index       index.html index.htm;
        listen      80 default_server;
        listen      [::]:80 default_server;
        add_header X-Served-By $HOSTNAME;
        location /redirect_me {
            return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
        error_page 404 /404.html;
        location /404 {
            root /var/www/html;
            internal;
        }
}
" > /etc/nginx/sites-available/default
service nginx restart
