#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo chown -R "$USER":"$USER" /etc/haproxy

echo "
    frontend http
    bind *:80
    mode http
    default_backend web-backend
    backend web-backend
    balance roundrobin
    server 3393-web-01 35.227.91.66:80 check
    server 3393-web-02 23.20.35.69:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
sudo service haproxy start
