#!/usr/bin/env bash
# commands to install mysql

sudo apt update
sudo apt install wget -y
wget https://dev.mysql.com/get/mysql-apt-config_0.8.12-1_all.deb
sudo dpkg -i mysql-apt-config_0.8.12-1_all.deb

sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 467B942D3A79BD29

sudo apt-get update
sudo apt-cache policy mysql-server
sudo apt install -f mysql-community-client=5.7.37-1ubuntu18.04

# Run in case of error
sudo apt install -f mysql-client=5.7.37-1ubuntu18.04

sudo apt install -f mysql-community-server=5.7.37-1ubuntu18.04

sudo apt install -f mysql-server=5.7.37-1ubuntu18.04