#!/usr/bin/env bash
# implementing the script 101-manage_my_process that manages the manage_my_process by using inputs start, restart and stop
case "${1}" in
"start")
echo "start"
    ;;
"restart")
echo "restart"
    ;;
"stop")
echo "stop"
    ;;
    *)
    ;;
esac