#!/usr/bin/env bash
# This script is displaying "Best School" 10 times, and in 9 prints hy

NUMBER=1
while [ "${NUMBER}" -le 10 ]
do
    NUMBER=$((NUMBER + 1))
    if [ "${NUMBER}" -eq 10 ]
    then
        echo "Hi"
        continue
    fi
        echo "Best School"
done

