#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes

HOURS=0
while [ "${HOURS}" -lt 12 ]
do
    MINUTS=0
    while [ "${MINUTS}" -lt 59 ]
    do
        MINUTS=$(( MINUTS + 1 ))
        echo "${MINUTS}"
    done
    HOURS=$(( HOURS + 1 ))
    echo "Hour: ${HOURS}"
done
